# scrutinizer-ci.com configuration
imports:
    - javascript
    - php
filter:
    excluded_paths:
        - webroot/
        - logs/
        - build/
        - node_modules/
        - tmp/
        - vendor/
checks:
    php: true
tools:
  external_code_coverage:
    runs: 1 # php 8.x versions
    timeout: 900 # 15 min

build:
  image: default-jammy # noble was not available on 12/09/2025
  nodes:
    analysis:
      environment:
        php: 8.4
      dependencies:
        before:
          - composer install
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
